#! /usr/bin/perl

use strict;
use warnings;
use File::Copy;

my $dir = $ARGV[0];
$dir =~ s/\/$//;

my $suffix = "";
if ($ARGV[1]){
	$suffix = $ARGV[1];
}

opendir(my $dh, $dir) or die "Error opening dir $dir";
my @files = readdir($dh);
@files = grep (!/^\./, @files);

foreach(@files){
	my $file = $dir."/".$_;
	open(my $fh, "<", $file) or die "Error opening Apache config file $file";
	my $serverName;
	while(<$fh>){
		if ($_ =~ /^\s*ServerName\s*(\S+)\s*$/i){
			$serverName = $1;
			last;
		}
	}
	close ($fh);
	if (!$serverName){
		print STDERR "WARN: Couldn't parse ServerName from $file\n";
	}else{
		$serverName =~ s/\s+/_/g;
		$serverName =~ s/^www\.//;
		my $newName = $dir."/".$serverName.$suffix;
		move($file, $newName);
	}
}
