#! /usr/bin/perl

# postfixdovecotmysql

# Installs and nearly configures a Postfix/Dovecot/MySQL/Postfixadmin mailer.

# Written by Avi in 2011

#Depends: libwww-perl, mysql-server, postfix

use strict;

eval{
	require LWP::Simple;
	LWP::Simple->import();
};
if($@){
	print "I need LWP::Simple, install libwww-perl\n";
	exit 1;
}


my $mysqluser = "root";
my $mysqlpass = $ARGV[0];

my $dovecotSqlFile = "/etc/dovecot/dovecot-sql.conf";

my $postfixDir = "/etc/postfix";
my $postfixMaincf = "/etc/postfix/main.cf";
my $postfixMastercf = "/etc/postfix/master.cf";
my $mailboxDir = "/var/vmail/";

my $dbuser = "postfix";
my $dbpass = `pwgen 25 1`;
chomp $dbpass;
my $dbhost = "localhost";
my $dbname = "postfix";

my $fqdn = `hostname -f`;
chomp $fqdn;

my $packages = "dovecot-common dovecot-imapd dovecot-pop3d postfix-mysql libapache2-mod-php5 php5-mysql php5-imap";

#### Postfixadmin-specific config  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

my $postfixadminURL = "http://downloads.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-2.3.3/postfixadmin-2.3.3.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fpostfixadmin%2F&ts=1303232343&use_mirror=ignum";
my $postfixadminDir = "/var/www/postfixadmin";
my $postfixadminPasswordHash = "0642ee71a7fce9b604697b60aaacef3e:d70d5bc659232de9f05fa758a24028604a8c30ae";
my $postfixadminPasswordPlain = "password";

my $postfixadminManual = <<EOF;

And then you can go and visit
  http://$fqdn/postfixadmin/setup.php
and create a new admin user using this setup password:
  $postfixadminPasswordPlain

Have Fun!

EOF

#### Postfix-specific config # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 


sub postfixCredentials() {
	return <<EOF;
user = $dbuser
password = $dbpass
hosts = $dbhost
dbname = $dbname
EOF
}

my %postfixFiles = (
	'mysql_virtual_alias_domain_catchall_maps'	=>  'query = SELECT goto FROM alias,alias_domain WHERE alias_domain.alias_domain = \'%d\' and alias.address = CONCAT(\'@\', alias_domain.target_domain) AND alias.active = 1 AND alias_domain.active=\'1\'',
	'mysql_virtual_alias_domain_mailbox_maps'	=>  'query = SELECT maildir FROM mailbox,alias_domain WHERE alias_domain.alias_domain = \'%d\' and mailbox.username = CONCAT(\'%u\', \'@\', alias_domain.target_domain) AND mailbox.active = 1 AND alias_domain.active=\'1\'',
	'mysql_virtual_alias_domain_maps'		=>  'query = SELECT goto FROM alias,alias_domain WHERE alias_domain.alias_domain = \'%d\' and alias.address = CONCAT(\'%u\', \'@\', alias_domain.target_domain) AND alias.active = 1 AND alias_domain.active=\'1\'',
	'mysql_virtual_alias_maps'			=>  'query = SELECT goto FROM alias WHERE address=\'%s\' AND active = \'1\'',
	'mysql_virtual_domains_maps'			=>  'query = SELECT domain FROM domain WHERE domain=\'%s\' AND active = \'1\'',
	'mysql_virtual_mailbox_maps'			=>  'query = SELECT maildir FROM mailbox WHERE username=\'%s\' AND active = \'1\'',
);

sub main_cf(){
	my $uid = shift;
	my $gid = shift;
	return <<EOF;
virtual_mailbox_domains = proxy:mysql:/etc/postfix//mysql_virtual_domains_maps.cf
virtual_alias_maps =
   proxy:mysql:$postfixDir/mysql_virtual_alias_maps.cf,
   proxy:mysql:$postfixDir/mysql_virtual_alias_domain_maps.cf,
   proxy:mysql:$postfixDir/mysql_virtual_alias_domain_catchall_maps.cf
virtual_mailbox_maps =
   proxy:mysql:$postfixDir/mysql_virtual_mailbox_maps.cf,
   proxy:mysql:$postfixDir/mysql_virtual_alias_domain_mailbox_maps.cf
virtual_uid_maps = static:$uid
virtual_gid_maps = static:$gid
EOF
}


sub master_cf() {
	return <<EOF;
dovecot   unix  -       n       n       -       -       pipe
  flags=DRhu user=vmail:mail argv=/usr/libexec/dovecot/deliver -d \${recipient}
EOF
}

#### Dovecot-specific config # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

sub dovecot_sql() {
my $uid = shift;
print <<EOF;
connect = host=$dbhost dbname=$dbname user=$dbuser password=$dbpass
driver = mysql
default_pass_scheme = MD5-CRYPT
password_query = SELECT username AS user,password FROM mailbox WHERE username = '%u' AND active='1'
user_query = SELECT maildir, $uid AS uid, 122 AS gid FROM mailbox WHERE username = '%u' AND active='1'
EOF
}

sub dovecotManual() {
	return <<EOF;
You now need to put this in the `auth default' block of /etc/dovecot/dovecot.conf:

  userdb sql {
    args = /etc/dovecot/dovecot-sql.conf
  }
  passdb sql {
    args = /etc/dovecot/dovecot-sql.conf
  }
EOF
}

sub dovecotAppend(){
	my $uid = shift;
	return "first_valid_uid: $uid\n";
}


### The bit where we do stuff # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 


my @installed = grep(/^ii/,`dpkg -l postfix mysql-server`);

#unless ( (grep(/^ii\s*postfix\s/, @installed)) && (grep(/^ii\s*mysql-server\s/, @installed)) ){
unless ($#installed >= 1){
	print STDERR "I need both the postfix and mysql-server packages installed and configured before I can begin.\n";
	exit 1;
}


if (!$mysqlpass){
	print "Please enter the password for mysql user \'$mysqluser\':\n";
	system('stty','-echo');
	chop($mysqlpass=<STDIN>);
	system('stty','echo');
}

print "Installing packages...";
`apt-get -y install $packages`;
print " done\n";

print "Restarting Apache2...";
`apache2ctl restart 2>&1 > /dev/null`;
print " done\n";

print "Creating user vmail...";
`useradd -r -g mail -d /var/vmail -s /sbin/nologin -c "Virtual mailbox" vmail`;
my $uid = getpwnam('vmail');
my $gid = getgrnam('mail');
chomp $uid;
print " done (UID: $uid)\n";

print "Creating mailbox dir ($mailboxDir)...";
`mkdir -p $mailboxDir`;
`chmod 770 $mailboxDir`;
`chown vmail.mail /var/vmail`;
print " done\n";

while ( my($file, $query) = each %postfixFiles ){
	my $file = $postfixDir."/".$file.".cf";
	print "Creating $file...";
	open(my $f, ">", $file) or die "Error opening postfix conf file $_ for writing. Does the dir exist?";
	print $f &postfixCredentials();
	print $f $query;
	close($f);
	print " done\n";
}

print "Creating $dovecotSqlFile...";
open (my $f, ">", $dovecotSqlFile) or die "Error opening dovecot SQL file ($dovecotSqlFile) for writing";
print $f &dovecot_sql($uid);
close($f);
print " done\n";

print "Appending to /etc/dovecot/dovecot.conf...";
open (my $f, ">>", "/etc/dovecot/dovecot.conf") or die "Error opening dovecot.conf (/etc/dovecot/dovecot.conf) for appending";
print $f &dovecotAppend();
close($f);
print " done\n";

print "Appending to $postfixMaincf...";
open (my $f, ">>", $postfixMaincf) or die "Error opening postfix's main.cf ($postfixMaincf) for writing";
print $f &main_cf($uid,$gid);
close($f);
print " done\n";

print "Appending to $postfixMastercf...";
open (my $f, ">>", $postfixMastercf);
print $f &master_cf;
close($f);
print " done\n";

print "Creating db...";
my $createdbCMD = "echo \"create database $dbname\" | mysql -u $mysqluser -p$mysqlpass";
`$createdbCMD`;
print " done\n";

print "Configuring db user...";
my $mysqlconnect = "mysql -u $mysqluser -p$mysqlpass";
my @mysqlCommands=(
#	"create database $dbname",
	"GRANT ALL PRIVILEGES ON $dbname.* TO $dbuser IDENTIFIED BY \'$dbpass\'",
#	"flush privileges"
);
foreach(@mysqlCommands){
	my $cmd = "echo \"$_\" | $mysqlconnect";
	`$cmd`;
}
print " done\n";

print "Getting postfixadmin...";
getstore($postfixadminURL, "/var/www/postfixadmin.tar.gz");
print " done\n";

print "Extracting postfixadmin...";
`tar -C /var/www -xf /var/www/postfixadmin.tar.gz`;
`mv /var/www/postfixadmin-* $postfixadminDir`;
print " done\n";

print "Configuring postfixadmin...";
open (my $f, "<", $postfixadminDir."/config.inc.php") or die "Error opening postifixadmin's config.inc.php";
my @config = <$f>;
close $f;
my @newconfig;
foreach(@config){
	my $line = $_;
	if ($line =~ /^\$CONF\[\'configured/){
		$line = "\$CONF['configured'] = true;\n";
	}elsif ($line =~ /^\$CONF\[\'database_user/){
		$line = "\$CONF[\'database_user\'] = \'$dbuser\';\n";
	}elsif ($line =~ /^\$CONF\[\'database_password/){
		$line = "\$CONF[\'database_password\'] = \'$dbpass\';\n";
	}elsif ($line =~ /^\$CONF\[\'database_name/){
		$line = "\$CONF[\'database_name\'] = \'$dbname\';\n";
	}elsif($line =~ /^\$CONF\[\'setup_password/){
		$line =  "\$CONF[\'setup_password\'] = \'$postfixadminPasswordHash\';\n";
	}

	push(@newconfig, $line);
}

open (my $f, ">", $postfixadminDir."/config.inc.php") or die "Error opening postfixadmin's config.inc.php for writing";
print $f join("", @newconfig);
close($f);
print " done\n";

print &dovecotManual();
print $postfixadminManual;
exit 0;


