#! /bin/bash
PASS=$(grep password /etc/mysql/debian.cnf | head -n1 | awk '{print $3}')
USER=debian-sys-maint
if [ "z$PASS" == "z" ]
then
	exit 1
fi

echo "show databases;" | mysql -u $USER -p$PASS &2>/dev/null
